-- MySQL Script generated by MySQL Workbench
-- Wed May 17 20:30:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Academia` DEFAULT CHARACTER SET utf8 ;
USE `Academia` ;

-- -----------------------------------------------------
-- Table `Academia`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Academia`.`Aluno` (
  `IdAluno` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(30) NOT NULL,
  `CPF` FLOAT NOT NULL,
  `NumTelefone` FLOAT NOT NULL,
  PRIMARY KEY (`IdAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Academia`.`Instrutor` (
  `IdInstrutor` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(30) NOT NULL,
  `CPF` FLOAT NOT NULL,
  PRIMARY KEY (`IdInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Academia`.`Aula` (
  `IdAula` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(30) NOT NULL,
  `QtdAlunos` FLOAT NOT NULL,
  `Horario` VARCHAR(10) NOT NULL,
  `Aluno_IdAluno` INT NOT NULL,
  `Instrutor_IdInstrutor` INT NOT NULL,
  PRIMARY KEY (`IdAula`, `Aluno_IdAluno`),
  INDEX `fk_Aula_Aluno1_idx` (`Aluno_IdAluno` ASC) ,
  INDEX `fk_Aula_Instrutor1_idx` (`Instrutor_IdInstrutor` ASC) ,
  CONSTRAINT `fk_Aula_Aluno1`
    FOREIGN KEY (`Aluno_IdAluno`)
    REFERENCES `Academia`.`Aluno` (`IdAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aula_Instrutor1`
    FOREIGN KEY (`Instrutor_IdInstrutor`)
    REFERENCES `Academia`.`Instrutor` (`IdInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia`.`Plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Academia`.`Plano` (
  `IdPlano` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdPlano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia`.`Plano_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Academia`.`Plano_Aluno` (
  `Plano_Id` INT NOT NULL,
  `Aluno_Id` INT NOT NULL,
  PRIMARY KEY (`Plano_Id`, `Aluno_Id`),
  INDEX `fk_Plano_has_Aluno_Aluno1_idx` (`Aluno_Id` ASC) ,
  INDEX `fk_Plano_has_Aluno_Plano1_idx` (`Plano_Id` ASC) ,
  CONSTRAINT `fk_Plano_has_Aluno_Plano1`
    FOREIGN KEY (`Plano_Id`)
    REFERENCES `Academia`.`Plano` (`IdPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plano_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_Id`)
    REFERENCES `Academia`.`Aluno` (`IdAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Academia`.`Grade_Exercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Academia`.`Grade_Exercicios` (
  `IdExercicios` INT NOT NULL AUTO_INCREMENT,
  `Aluno_IdAluno` INT NOT NULL,
  `Instrutor_IdInstrutor` INT NOT NULL,
  PRIMARY KEY (`IdExercicios`),
  INDEX `fk_Grade_Exercicios_Aluno1_idx` (`Aluno_IdAluno` ASC) ,
  INDEX `fk_Grade_Exercicios_Instrutor1_idx` (`Instrutor_IdInstrutor` ASC) ,
  CONSTRAINT `fk_Grade_Exercicios_Aluno1`
    FOREIGN KEY (`Aluno_IdAluno`)
    REFERENCES `Academia`.`Aluno` (`IdAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grade_Exercicios_Instrutor1`
    FOREIGN KEY (`Instrutor_IdInstrutor`)
    REFERENCES `Academia`.`Instrutor` (`IdInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
